enum SCREENS {
    AUTH = "AUTH",
    APP = "APP",
    LANDING = "LANGING",
    PHONE = "PHONE",
    OTP = "OTP",
    PROFILE_NAME = "PROFILE_NAME",
    PROFILE_IMAGE = "PROFILE_IMAGE",
    HOME = "HOME",
    MESSAGES = "MESSAGES",
    CALLS = "CALLS",
    WALLET = "WALLET",
    CONTACTS = "CONTACTS",
    NEWS = "NEWS",
    CHAT = "CHAT",
    NEWS_DETAIL = "NEWS_DETAIL",
    WALLET_HOME = "WALLET_HOME",
    SEND = "SEND",
    SEND_SUMMARY = "SEND_SUMMARY",
    SEND_SUCCESS = "SEND_SUCCESS",
    TRANSACTION_HISTORY = "TRANSACTION_HISTORY",
    HISTORY_SETTING = "HISTORY_SETTING",
    RECIEVE = "RECIEVE",
    SETTING = "SETTING",
    EDIT_PROFILE = "EDIT_PROFILE",
    DISPLAY_SETTING = "DISPLAY_SETTING",
    CHAT_SETTING = "CHAT_SETTING",
    LANG_SETTING = "LANG_SETTING",
    NOTIFICATION_SETTING = "NOTIFICATION_SETTING",
    WALLPAPER_SETTING = "WALLPAPER_SETTING",
    BLOCKED_CONTACTS = "BLOCKED_CONTACTS"
}

enum ASYNC_KEYS {
    ACTIVE_THEME = "@ACTIVE_THEME",
    CHAT_FONT_SIZE = "@CHAT_FONT_SIZE"
}

enum ROUTES {

}

enum THEMES {
    DEFAULT = "Default",
    LIGHT = "Light",
    DARK = "Dark"
}

enum CHAT_FONT_SIZE {
    SMALL = "Small",
    MEDIUM = "Medium",
    LARGE = "Large"
}

export {
    SCREENS,
    ASYNC_KEYS,
    ROUTES,
    THEMES,
    CHAT_FONT_SIZE
}