enum SCREENS {
    AUTH = "AUTH",
    APP = "APP",
    LANDING = "LANGING",
    PHONE = "PHONE",
    OTP = "OTP",
    PROFILE_NAME = "PROFILE_NAME",
    PROFILE_IMAGE = "PROFILE_IMAGE",
    HOME = "HOME",
    MESSAGES = "MESSAGES",
    CALLS = "CALLS",
    WALLET = "WALLET",
    CONTACTS = "CONTACTS",
    NEWS = "NEWS",
    CHAT = "CHAT",
    NEWS_DETAIL = "NEWS_DETAIL",
    SEND = "SEND",
    TRANSACTION_HISTORY = "TRANSACTION_HISTORY",
    HISTORY_SETTING = "HISTORY_SETTING",
}

enum ASYNC_KEYS {

}

enum ROUTES {

}

export {
    SCREENS,
    ASYNC_KEYS,
    ROUTES
}